version: '3'

services:

  mosquito:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
    - "1883:1883"
    - "9001:9001"
    restart: always

# Discovers automatically the os architecture (armv6, armv7 etc..)
  nodered:
    image: nodered/node-red:latest-minimal
    container_name: nodered
    ports:
    - "1880:1880"
    volumes:
     - ./node-red:/data
    restart: always


#  python_main:
#    image: python-container
#    container_name: pymain
#   # restart: always
#    volumes:
#     - ./:/smart-home
#     - /data/text_to_speech:/data/text_to_speech
#    privileged: true

  rpi-monitor:
    image: michaelmiklis/rpi-monitor:latest
    container_name: rpi-monitor
    restart: always
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    ports:
      - 8888:8888
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"


  # portainer:
    # image: portainer/portainer
    # container_name: portainer
    # command: -H unix:///var/run/docker.sock
    # restart: always
    # ports:
      # - 9000:9000
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # - portainer_data:/data

  ngrok:
    image: wernight/ngrok:armhf
    container_name: ngrok
    command: http nodered:80
    restart: always
    ports:
      - 4040:4040

volumes:
  portainer_data:
