version: '2'

services:

  mosquito:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
    - "1883:1883"
    - "9001:9001"
    environment:
    - test_var=-Xmx2048m
    restart: always

  nodered:
    image: nodered/node-red:1.0.2-10-arm32v7
    container_name: nodered
    ports:
    - "1880:1880"
    volumes:
     - ./node-red:/data
    environment:
    - test_var=-Xmx2048m
    restart: always
    #    privileged: true


#  python_main:
#    image: python-container
#    container_name: pymain
#   # restart: always
#    volumes:
#     - ./:/smart-home
#     - /data/text_to_speech:/data/text_to_speech
#    privileged: true

  rpi-monitor:
    image: michaelmiklis/rpi-monitor:latest
    container_name: rpi-monitor
    restart: always
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    ports:
      - 8888:8888
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm:/dev/vcsm"


  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
